"""tram-mcp launcher.

The launcher's job is to keep Claude Desktop's MCP handshake fast even when
loading the underlying FastMCP server is slow (e.g. when corporate EDR tooling
rescans every .pyc file on each Python process spawn). It splits the work
into two phases:

  Phase 1 (parent / proxy):
    - Pre-bake the static parts of an MCP `initialize` response and ship it
      back to the client as soon as the request arrives. No heavy imports.
    - Spawn a child process (this same module, with `TRAM_MCP_CHILD=1`) which
      loads FastMCP and runs the real server.
    - Intercept `tools/list` requests and serve them from a JSON file
      captured at build time (tram_mcp/tools_static.json). Clients see the
      full tool catalog instantly without waiting for FastMCP to import.
    - Forward all other stdio traffic between client and child. Tool *calls*
      still go to the child; if it isn't ready yet, the request blocks in
      its stdin until it is.

  Phase 2 (child / real server):
    - `TRAM_MCP_CHILD=1` short-circuits the proxy path. The child imports
      FastMCP, builds the tool catalog, then runs `mcp.run()` as before.
    - The parent forwards the original `initialize` to the child first so
      FastMCP reaches its `initialized` state internally; the child's own
      initialize response is then drained and discarded (the parent already
      sent one to the client).

Pre-baked response correctness: the `capabilities`, `serverInfo`,
`instructions`, and `tools/list` payload returned by Phase 1 must match
what FastMCP would have returned. The tools list is regenerated by
``scripts/regenerate_static_tools.py``; the consistency test in
``tests/test_launcher.py`` compares it against a fresh capture and fails
loudly on drift.

Set `TRAM_MCP_NO_LAUNCHER=1` to disable the proxy entirely and run the legacy
single-process path. Useful for debugging.
"""

from __future__ import annotations

import json
import os
import pathlib
import subprocess
import sys
import threading
from importlib.metadata import version as _pkg_version

try:
    __version__ = _pkg_version("tram-mcp")
except Exception:
    __version__ = "unknown"


_INSTRUCTIONS = (
    "Use this server when the user mentions TestRail, Test Rail, "
    "test cases, test runs, test results, test steps, test plans, "
    "test suites, test milestones, test configurations, QA, "
    "quality assurance, test management, or test reporting. "
    "Start with browse_testrail_api to discover available categories, "
    "then describe_testrail_method to learn how to call a specific method, "
    "then run_testrail_command to execute it. "
    "Use search_test_cases for quick title-based case lookups."
)

_PREBAKED_CAPABILITIES = {
    "experimental": {},
    "logging": {},
    "prompts": {"listChanged": False},
    "resources": {"subscribe": False, "listChanged": False},
    "tools": {"listChanged": True},
    "extensions": {"io.modelcontextprotocol/ui": {}},
}


def _load_static_tools() -> list[dict] | None:
    """Return the tools/list payload captured at build time, or None if the
    file isn't present (development install before running the regenerate
    script). When None, the launcher falls back to forwarding tools/list to
    the child and pays the cold-start cost there."""
    p = pathlib.Path(__file__).with_name("tools_static.json")
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


_STATIC_TOOLS = _load_static_tools()


def _log(msg: str) -> None:
    print(f"[tram-mcp launcher v{__version__}] {msg}", file=sys.stderr, flush=True)


def _run_real_server() -> int:
    """In-process FastMCP server. Used by the child (TRAM_MCP_CHILD=1) and
    by the no-launcher fallback path."""
    from tram_mcp._autoupdate import spawn_background_upgrade
    from tram_mcp.server import mcp

    print(f"[tram-mcp] starting v{__version__}", file=sys.stderr, flush=True)
    spawn_background_upgrade()
    mcp.run(log_level="WARNING")
    return 0


def _build_initialize_response(init_msg: dict) -> dict:
    requested_proto = init_msg.get("params", {}).get("protocolVersion", "2025-11-25")
    return {
        "jsonrpc": "2.0",
        "id": init_msg.get("id"),
        "result": {
            "protocolVersion": requested_proto,
            "capabilities": _PREBAKED_CAPABILITIES,
            "serverInfo": {"name": "TestRail MCP", "version": __version__},
            "instructions": _INSTRUCTIONS,
        },
    }


def _proxy(initial_msg: dict, initial_line: bytes) -> int:
    """Spawn the real server and forward stdio between client and child.

    `initial_msg` is the already-parsed `initialize` request; `initial_line`
    is the exact bytes we read from stdin (sent to the child verbatim so its
    own JSON parser stays happy).
    """
    env = os.environ.copy()
    env["TRAM_MCP_CHILD"] = "1"

    # Use the same Python interpreter so we stay inside the installed venv.
    child = subprocess.Popen(
        [sys.executable, "-m", "tram_mcp"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=None,  # inherit parent's stderr so child logs surface in Claude Desktop's log
        env=env,
        bufsize=0,
    )

    # Hand the original initialize to the child so it reaches the
    # `initialized` state internally. The child will eventually respond
    # with its own initialize result; the child_to_client thread filters
    # that out (we've already sent ours to the parent).
    try:
        child.stdin.write(initial_line if initial_line.endswith(b"\n") else initial_line + b"\n")
        child.stdin.flush()
    except (BrokenPipeError, OSError) as e:
        _log(f"child died before init handoff: {e}")
        return 1

    init_id = initial_msg.get("id")
    write_lock = threading.Lock()

    def _write_to_client(payload: bytes) -> None:
        with write_lock:
            try:
                sys.stdout.buffer.write(payload)
                sys.stdout.buffer.flush()
            except (BrokenPipeError, OSError):
                pass

    def client_to_child() -> None:
        """Read from client stdin; intercept tools/list, forward the rest."""
        try:
            while True:
                data = sys.stdin.buffer.readline()
                if not data:
                    break

                # Short-circuit tools/list with the build-time capture.
                # Anything we can't parse falls through to plain forwarding.
                if _STATIC_TOOLS is not None:
                    try:
                        msg = json.loads(data)
                    except (json.JSONDecodeError, UnicodeDecodeError):
                        msg = None
                    if isinstance(msg, dict) and msg.get("method") == "tools/list":
                        resp = {
                            "jsonrpc": "2.0",
                            "id": msg.get("id"),
                            "result": {"tools": _STATIC_TOOLS},
                        }
                        _write_to_client((json.dumps(resp) + "\n").encode("utf-8"))
                        continue

                child.stdin.write(data)
                child.stdin.flush()
        except (BrokenPipeError, OSError):
            pass
        finally:
            try:
                child.stdin.close()
            except OSError:
                pass

    def child_to_client() -> None:
        """Read from child stdout; drop the duplicate initialize response,
        forward everything else."""
        init_drained = False
        try:
            while True:
                data = child.stdout.readline()
                if not data:
                    break

                if not init_drained:
                    # Try to identify whether this is the child's response
                    # to our forwarded initialize request. If so, swallow
                    # it. If parsing fails or it's some other message
                    # (rare but possible during slow startup), forward it.
                    try:
                        msg = json.loads(data)
                    except (json.JSONDecodeError, UnicodeDecodeError):
                        msg = None
                    if (
                        isinstance(msg, dict)
                        and msg.get("id") == init_id
                        and "result" in msg
                    ):
                        init_drained = True
                        continue

                _write_to_client(data)
        except (BrokenPipeError, OSError):
            pass

    t_in = threading.Thread(target=client_to_child, daemon=True)
    t_out = threading.Thread(target=child_to_client, daemon=True)
    t_in.start()
    t_out.start()

    return child.wait()


def main() -> int:
    # Escape hatches: the child (re-invoked via `python -m tram_mcp` with
    # TRAM_MCP_CHILD=1) and the explicit single-process opt-out both run the
    # real server in-process. Same for environments where stdio can't be
    # cleanly proxied (e.g. when stdin isn't a pipe).
    if os.environ.get("TRAM_MCP_CHILD") == "1" or os.environ.get("TRAM_MCP_NO_LAUNCHER") == "1":
        return _run_real_server()
    if not sys.stdin or sys.stdin.isatty():
        return _run_real_server()

    # Phase 1: read the first message. It MUST be an `initialize` request per
    # the MCP spec; if it isn't, we bail out rather than guess.
    initial_line = sys.stdin.buffer.readline()
    if not initial_line:
        return 0
    try:
        init_msg = json.loads(initial_line)
    except json.JSONDecodeError as e:
        _log(f"first message wasn't valid JSON ({e}); cannot proxy")
        return 1

    if init_msg.get("method") != "initialize":
        _log(f"first message method was {init_msg.get('method')!r}, not 'initialize'; falling back to in-process server")
        # Best-effort: hand the message to the real server. We can't put bytes
        # back on stdin, but we can stash them and let _run_real_server handle
        # them via a pre-fed input. Simplest fallback: write them and run.
        # (Not expected in practice with conforming clients.)
        os.environ["TRAM_MCP_CHILD"] = "1"
        return _run_real_server()

    # Phase 1 response: respond to initialize before loading FastMCP.
    response = _build_initialize_response(init_msg)
    sys.stdout.buffer.write((json.dumps(response) + "\n").encode("utf-8"))
    sys.stdout.buffer.flush()

    # Phase 2: spawn child + forward all further traffic.
    return _proxy(init_msg, initial_line)
